const promptArr = [
    "A realistic image of a cityscape on a distant planet with three moons hanging in the sky.",
    "A realistic image of a mystical forest where the trees glow with bioluminescent light.",
    "A realistic image of a steampunk metropolis bustling with airships and mechanical wonders.",
    "A realistic image of a serene lake surrounded by snow-capped mountains reflecting in its crystal-clear waters.",
    "A realistic image of a underwater civilization built within the ruins of an ancient temple.",
    "A realistic image of a futuristic skyline dominated by towering skyscrapers and flying cars.",
    "A realistic image of a hidden garden filled with exotic plants and magical creatures.",
    "A realistic image of a post-apocalyptic wasteland reclaimed by nature with remnants of civilization scattered throughout.",
    "A realistic image of a fantastical realm where dragons soar through the skies and wizards conjure spells.",
    "A realistic image of a cyberpunk street scene illuminated by neon lights and holographic advertisements.",
    "A realistic image of a enchanted castle perched on a cliff overlooking the sea.",
    "A realistic image of a space station orbiting a distant star, with astronauts floating weightlessly outside.",
    "A realistic image of a giant mechanical robot standing guard over a futuristic city.",
    "A realistic image of a village nestled in the clouds, accessible only by flying ships.",
    "A realistic image of a group of adventurers exploring a hidden cave filled with treasure.",
    "A realistic image of a magical library filled with ancient books and mystical artifacts.",
    "A realistic image of a post-apocalyptic survivor wandering through a desolate landscape.",
    "A realistic image of a colony on Mars with domed habitats and terraformed landscapes.",
    "A realistic image of a lush jungle teeming with exotic wildlife and hidden ruins.",
    "A realistic image of a alien marketplace bustling with creatures from across the galaxy.",
    "A realistic image of a wizard's tower surrounded by swirling mists and arcane symbols.",
    "A realistic image of a futuristic arena where robots battle for supremacy.",
    "A realistic image of a snow-covered village celebrating a winter festival.",
    "A realistic image of a caravan of nomads crossing a desert wasteland on mechanical camels.",
    "A realistic image of a abandoned spaceship drifting through the void of space.",
    "A realistic image of a magical waterfall cascading into a hidden lagoon.",
    "A realistic image of a floating city held aloft by giant balloons and airships.",
    "A realistic image of a volcanic island inhabited by fire-breathing dragons.",
    "A realistic image of a futuristic laboratory conducting experiments on time travel.",
    "A realistic image of a mythical creature emerging from the depths of a dark forest.",
    "A realistic image of a group of explorers charting uncharted territories on a distant planet.",
    "A realistic image of a futuristic dystopia where technology has enslaved humanity.",
    "A realistic image of a celestial being descending from the heavens to impart wisdom.",
    "A realistic image of a fantastical carnival with rides powered by magic.",
    "A realistic image of a secret underground bunker hiding advanced technology.",
    "A realistic image of a haunted mansion filled with restless spirits.",
    "A realistic image of a ancient coliseum where gladiators battle mythical beasts.",
    "A realistic image of a magical portal leading to other dimensions.",
    "A realistic image of a fleet of starships engaged in a space battle against alien invaders.",
    "A realistic image of a hidden laboratory conducting experiments on genetic engineering.",
    "A realistic image of a medieval kingdom under siege by dark forces.",
    "A realistic image of a futuristic cityscape where buildings are grown rather than constructed.",
    "A realistic image of a group of adventurers journeying through a dark and dangerous forest.",
    "A realistic image of a abandoned amusement park reclaimed by nature.",
    "A realistic image of a time-traveling adventurer exploring ancient civilizations.",
    "A realistic image of a celestial alignment causing strange phenomena on a distant world.",
    "A realistic image of a secret society conducting rituals in a hidden underground chamber.",
    "A realistic image of a group of rebels fighting against a tyrannical regime in a dystopian future.",
    "A realistic image of a magical artifact hidden within a labyrinthine dungeon.",
    "A realistic image of a city submerged beneath the ocean, now inhabited by aquatic creatures.",
    "A realistic image of a fantastical garden inhabited by sentient plants and animals.",
    "A realistic image of a intergalactic highway stretching across the cosmos.",
    "A realistic image of a futuristic city where humans and robots coexist.",
    "A realistic image of a lost civilization discovered deep within the Amazon rainforest.",
    "A realistic image of a alien invasion force descending upon Earth.",
    "A realistic image of a group of time travelers witnessing key moments in history.",
    "A realistic image of a mystical mountain peak shrouded in eternal mist.",
    "A realistic image of a tribe of warriors riding giant beasts into battle.",
    "A realistic image of a forgotten temple hidden within a dense jungle.",
    "A realistic image of a space colony threatened by a rogue asteroid.",
    "A realistic image of a city skyline illuminated by a meteor shower.",
    "A realistic image of a magical forest where trees come to life at night.",
    "A realistic image of a group of wizards dueling in a magical arena.",
    "A realistic image of a futuristic utopia where humanity has transcended its physical form.",
    "A realistic image of a sunken city inhabited by merfolk and sea monsters.",
    "A realistic image of a team of explorers searching for lost treasures in the desert.",
    "A realistic image of a civilization living in harmony with nature on a distant planet.",
    "A realistic image of a ancient prophecy foretelling the end of the world.",
    "A realistic image of a network of underground tunnels connecting secret hideouts.",
    "A realistic image of a group of space explorers discovering a new habitable planet.",
    "A realistic image of a cityscape transformed by a sudden ice age.",
    "A realistic image of a hidden valley untouched by time, home to creatures long extinct.",
    "A realistic image of a magical academy training the next generation of wizards.",
    "A realistic image of a group of survivors navigating a post-apocalyptic landscape.",
    "A realistic image of a futuristic megalopolis stretching as far as the eye can see.",
    "A realistic image of a colony of aliens living beneath the surface of Mars.",
    "A realistic image of a labyrinthine city filled with twisting alleyways and hidden passages.",
    "A realistic image of a team of archaeologists uncovering the ruins of an ancient civilization.",
    "A realistic image of a futuristic prison floating in space.",
    "A realistic image of a group of explorers braving the dangers of an alien jungle.",
    "A realistic image of a underground rebellion plotting to overthrow a corrupt government.",
    "A realistic image of a legendary sword buried deep within a mountain.",
    "A realistic image of a group of superheroes defending the city from supervillains.",
    "A realistic image of a futuristic society controlled by artificial intelligence.",
    "A realistic image of a magical kingdom ruled by a benevolent queen.",
    "A realistic image of a team of scientists racing to prevent a global catastrophe.",
    "A realistic image of a hidden cave system containing ancient artifacts.",
    "A realistic image of a colony on a distant moon facing a rebellion.",
    "A realistic image of a mystical island where time flows differently.",
    "A realistic image of a space station orbiting a black hole.",
    "A realistic image of a group of survivors stranded on a deserted island.",
    "A realistic image of a ancient prophecy foretelling the return of an ancient evil.",
    "A realistic image of a futuristic cityscape where nature has reclaimed the urban landscape.",
    "A realistic image of a team of explorers discovering a lost civilization in Antarctica.",
    "A realistic image of a magical portal opening to a realm of pure chaos.",
    "A realistic image of a group of adventurers journeying to the center of the Earth.",
    "A realistic image of a ancient temple hidden within a remote mountain range.",
    "A realistic image of a space-faring civilization on the brink of collapse.",
    "A realistic image of a group of rebels fighting against a tyrannical alien empire.",
    "A realistic image of a futuristic society where memories can be implanted and altered.",
    "A realistic image of a hidden city deep within the jungle, protected by ancient magic.",
    "A realistic image of a intergalactic war spanning across multiple star systems.",
    "A realistic image of a group of time travelers attempting to alter the course of history.",
    "A realistic image of a cybernetic city populated by humans and androids.",
    "A realistic image of a team of explorers uncovering the truth behind a government conspiracy.",
    "A realistic image of a magical ring imbued with untold power.",
    "A realistic image of a group of astronauts stranded on a distant planet.",
    "A realistic image of a ancient curse unleashed upon a modern city.",
    "A realistic image of a society where dreams are harvested and sold as commodities.",
    "A realistic image of a hidden valley inhabited by mythical creatures.",
    "A realistic image of a futuristic society where music is outlawed.",
    "A realistic image of a team of adventurers exploring a network of underground tunnels.",
    "A realistic image of a colony on a distant planet facing environmental collapse.",
    "A realistic image of a group of rebels fighting against a dystopian regime.",
    "A realistic image of a mystical artifact hidden within a cursed tomb.",
    "A realistic image of a cityscape overtaken by a sentient AI.",
    "A realistic image of a underground resistance fighting against alien invaders.",
    "A realistic image of a group of explorers uncovering the ruins of an ancient civilization beneath the ocean floor.",
    "A realistic image of a dystopian society where emotions are forbidden.",
    "A realistic image of a team of scientists conducting experiments on a remote island.",
    "A realistic image of a ancient prophecy foretelling the rise of a new hero.",
    "A realistic image of a magical forest guarded by mythical creatures.",
    "A realistic image of a society divided between the rich living in luxury and the poor struggling to survive.",
    "A realistic image of a group of adventurers journeying to the center of the galaxy.",
    "A realistic image of a abandoned space station haunted by the ghosts of its former crew.",
    "A realistic image of a futuristic cityscape where the rich live in floating palaces above the clouds.",
    "A realistic image of a team of explorers uncovering the remains of an ancient alien civilization.",
    "A realistic image of a group of rebels fighting against a totalitarian regime.",
    "A realistic image of a hidden city hidden within the depths of a jungle.",
    "A realistic image of a society where technology has advanced to the point of replacing human labor.",
    "A realistic image of a team of astronauts on a mission to colonize a distant planet.",
    "A realistic image of a ancient prophecy foretelling the return of an ancient evil.",
    "A realistic image of a post-apocalyptic society rebuilding civilization from the ashes.",
    "A realistic image of a hidden valley inhabited by a tribe of peaceful giants.",
    "A realistic image of a futuristic cityscape where robots have surpassed humans in intelligence.",
    "A realistic image of a team of adventurers exploring a mysterious pyramid in the desert.",
    "A realistic image of a society where people are born with magical abilities.",
    "A realistic image of a underground rebellion fighting against a tyrannical government.",
    "A realistic image of a group of explorers uncovering the lost city of Atlantis.",
    "A realistic image of a colony on a distant planet facing an alien invasion.",
    "A realistic image of a team of superheroes battling against an army of supervillains.",
    "A realistic image of a futuristic society where the Earth is a barren wasteland.",
    "A realistic image of a group of time travelers attempting to prevent a catastrophic event.",
    "A realistic image of a society where the dead can be brought back to life as cyborgs.",
    "A realistic image of a ancient artifact hidden within a cursed temple.",
    "A realistic image of a team of explorers uncovering the truth behind a government conspiracy.",
    "A realistic image of a colony on a distant planet facing environmental collapse.",
    "A realistic image of a group of rebels fighting against a dystopian regime.",
    "A realistic image of a mystical artifact hidden within a cursed tomb.",
    "A realistic image of a cityscape overtaken by a sentient AI.",
    "A realistic image of a underground resistance fighting against alien invaders.",
    "A realistic image of a group of explorers uncovering the ruins of an ancient civilization beneath the ocean floor.",
    "A realistic image of a dystopian society where emotions are forbidden.",
    "A realistic image of a team of scientists conducting experiments on a remote island.",
    "A realistic image of a ancient prophecy foretelling the rise of a new hero.",
    "A realistic image of a magical forest guarded by mythical creatures.",
    "A realistic image of a society divided between the rich living in luxury and the poor struggling to survive.",
    "A realistic image of a group of adventurers journeying to the center of the galaxy.",
    "A realistic image of a abandoned space station haunted by the ghosts of its former crew.",
    "A realistic image of a futuristic cityscape where the rich live in floating palaces above the clouds.",
    "A realistic image of a team of explorers uncovering the remains of an ancient alien civilization.",
    "A realistic image of a group of rebels fighting against a totalitarian regime.",
    "A realistic image of a hidden city hidden within the depths of a jungle.",
    "A realistic image of a society where technology has advanced to the point of replacing human labor.",
    "A realistic image of a team of astronauts on a mission to colonize a distant planet.",
    "A realistic image of a ancient prophecy foretelling the return of an ancient evil.",
    "A realistic image of a post-apocalyptic society rebuilding civilization from the ashes.",
    "A realistic image of a hidden valley inhabited by a tribe of peaceful giants.",
    "A realistic image of a futuristic cityscape where robots have surpassed humans in intelligence.",
    "A realistic image of a team of adventurers exploring a mysterious pyramid in the desert.",
    "A realistic image of a society where people are born with magical abilities.",
    "A realistic image of a underground rebellion fighting against a tyrannical government.",
    "A realistic image of a group of explorers uncovering the lost city of Atlantis.",
    "A realistic image of a colony on a distant planet facing an alien invasion.",
    "A realistic image of a team of superheroes battling against an army of supervillains.",
    "A realistic image of a futuristic society where the Earth is a barren wasteland.",
    "A realistic image of a group of time travelers attempting to prevent a catastrophic event.",
    "A realistic image of a society where the dead can be brought back to life as cyborgs.",
    "A realistic image of a ancient artifact hidden within a cursed temple.",
    "A realistic image of a bustling city street filled with people and traffic.",
    "A realistic image of a tranquil countryside scene with rolling hills and grazing livestock.",
    "A realistic image of a serene beach at sunset with waves crashing gently on the shore.",
    "A realistic image of a cozy cabin nestled in the woods with smoke rising from the chimney.",
    "A realistic image of a majestic mountain peak towering above the clouds.",
    "A realistic image of a vast desert landscape stretching to the horizon.",
    "A realistic image of a peaceful river winding its way through a lush forest.",
    "A realistic image of a rustic farmhouse surrounded by fields of golden wheat.",
    "A realistic image of a bustling market square with vendors selling their wares.",
    "A realistic image of a quiet park with trees in full bloom and children playing.",
    "A realistic image of a quaint village nestled in a valley surrounded by mountains.",
    "A realistic image of a busy harbor with ships coming and going.",
    "A realistic image of a lively carnival with rides, games, and colorful decorations.",
    "A realistic image of a vibrant coral reef teeming with marine life.",
    "A realistic image of a snowy landscape with evergreen trees dusted in white.",
    "A realistic image of a starry night sky with the Milky Way stretching across it.",
    "A realistic image of a thunderstorm with lightning illuminating the dark clouds.",
    "A realistic image of a field of sunflowers swaying in the breeze.",
    "A realistic image of a historic castle perched on a hilltop overlooking the countryside.",
    "A realistic image of a busy airport with planes taking off and landing.",
    "A realistic image of a dense fog rolling in over a city skyline.",
    "A realistic image of a peaceful meadow with wildflowers in bloom.",
    "A realistic image of a bustling cafe with patrons enjoying coffee and conversation.",
    "A realistic image of a picturesque waterfall cascading into a crystal-clear pool.",
    "A realistic image of a quaint cobblestone street lined with shops and cafes.",
    "A realistic image of a colorful hot air balloon floating above the clouds.",
    "A realistic image of a majestic oak tree standing alone in a field.",
    "A realistic image of a winding country road leading through rolling hills.",
    "A realistic image of a serene lake surrounded by towering pine trees.",
    "A realistic image of a dramatic sunset painting the sky in shades of orange and pink.",
    "A realistic image of a cozy fireplace with crackling flames and glowing embers.",
    "A realistic image of a peaceful garden with blooming flowers and chirping birds.",
    "A realistic image of a quiet library with rows of books and reading nooks.",
    "A realistic image of a picturesque vineyard with rows of grapevines stretching into the distance.",
    "A realistic image of a bustling train station with commuters rushing to catch their trains.",
    "A realistic image of a quaint cottage with a thatched roof and flower-filled garden.",
    "A realistic image of a snowy forest blanketed in white with icicles hanging from the trees.",
    "A realistic image of a charming lighthouse overlooking the ocean.",
    "A realistic image of a rocky coastline with waves crashing against the cliffs.",
    "A realistic image of a tranquil zen garden with raked sand and carefully placed stones.",
    "A realistic image of a peaceful riverbank with ducks swimming in the water.",
    "A realistic image of a quaint covered bridge spanning a babbling brook.",
    "A realistic image of a bustling city square with street performers and market stalls.",
    "A realistic image of a cozy log cabin surrounded by a blanket of snow.",
    "A realistic image of a vibrant city skyline illuminated by fireworks.",
    "A realistic image of a sun-drenched vineyard with grapevines stretching as far as the eye can see.",
    "A realistic image of a peaceful pond with lily pads floating on the surface.",
    "A realistic image of a charming village church with a steeple reaching towards the sky.",
    "A realistic image of a lively street market with vendors selling fresh produce and handmade goods.",
    "A realistic image of a tranquil forest glade with sunlight filtering through the trees.",
    "A realistic image of a bustling city harbor with ships of all sizes coming and going.",
    "A realistic image of a quaint seaside town with colorful houses lining the shore.",
    "A realistic image of a picturesque mountain lake reflecting the surrounding peaks.",
    "A realistic image of a rustic log cabin nestled in a clearing in the woods.",
    "A realistic image of a busy city intersection with cars and pedestrians going about their day.",
    "A realistic image of a peaceful orchard with fruit trees in full bloom.",
    "A realistic image of a quaint village square with a fountain in the center.",
    "A realistic image of a serene forest pond with frogs croaking and dragonflies darting about.",
    "A realistic image of a bustling city market with vendors selling fresh produce and street food.",
    "A realistic image of a tranquil garden patio with a bubbling fountain and lush greenery.",
    "A realistic image of a charming country church surrounded by fields of wildflowers.",
    "A realistic image of a vibrant city park with people picnicking and playing frisbee.",
    "A realistic image of a cozy mountain cabin with smoke curling from the chimney.",
    "A realistic image of a bustling city square with historic buildings and street performers.",
    "A realistic image of a peaceful river bend with willow trees swaying in the breeze.",
    "A realistic image of a picturesque coastal village with fishing boats bobbing in the harbor.",
    "A realistic image of a tranquil forest glen with a bubbling brook running through it.",
    "A realistic image of a bustling city alleyway with shops and cafes.",
    "A realistic image of a quaint country cottage with a thatched roof and flower-filled garden.",
    "A realistic image of a vibrant city street with colorful storefronts and bustling crowds.",
    "A realistic image of a peaceful country lane with hedgerows and wildflowers.",
    "A realistic image of a bustling city waterfront with boats moored at the docks.",
    "A realistic image of a charming village square with a market in full swing.",
    "A realistic image of a tranquil woodland clearing with sunlight streaming through the trees.",
    "A realistic image of a bustling city avenue with skyscrapers reaching towards the sky.",
    "A realistic image of a serene garden pond with koi fish swimming lazily beneath the surface.",
    "A realistic image of a quaint seaside cafe with tables overlooking the ocean.",
    "A realistic image of a bustling city thoroughfare with cars and buses rushing past.",
    "A realistic image of a peaceful country meadow with wildflowers in bloom.",
    "A realistic image of a picturesque mountain village nestled in a valley.",
    "A realistic image of a lively city square with street performers and outdoor cafes.",
    "A realistic image of a tranquil forest stream with water cascading over moss-covered rocks.",
    "A realistic image of a bustling city promenade with shops and restaurants.",
    "A realistic image of a cozy country inn with a warm fire crackling in the hearth.",
    "A realistic image of a vibrant city boulevard with trees lining the sidewalks.",
    "A realistic image of a serene mountain pass with snow-capped peaks in the distance.",
    "A realistic image of a bustling city market with vendors selling fresh produce and handmade crafts.",
    "A realistic image of a peaceful country lane bordered by fields of wildflowers.",
    "A realistic image of a quaint village green with children playing and dogs frolicking.",
    "A realistic image of a tranquil forest glade with a carpet of bluebells.",
    "A realistic image of a bustling city plaza with fountains and flower beds.",
    "A realistic image of a cozy mountain chalet nestled in the snow-covered peaks.",
    "A realistic image of a lively city boardwalk with shops and amusement rides.",
    "A realistic image of a peaceful country road winding through rolling hills.",
    "A realistic image of a bustling city market with vendors selling fresh seafood and local produce.",
    "A realistic image of a serene woodland pond with ducks paddling in the water.",
    "A realistic image of a picturesque coastal path winding along rugged cliffs.",
    "A realistic image of a tranquil forest clearing with a carpet of fallen leaves.",
    "A realistic image of a bustling city square with historic architecture and outdoor cafes.",
    "A realistic image of a cozy village inn with ivy-covered walls and a welcoming fireplace.",
    "A realistic image of a vibrant city boulevard with street musicians and outdoor art installations.",
    "A realistic image of a serene mountain lake surrounded by pine forests and rocky peaks.",
    "A realistic image of a bustling city market with stalls selling exotic spices and textiles.",
    "A realistic image of a peaceful country lane bordered by blooming wildflowers.",
    "A realistic image of a quaint village green with a cricket match in progress.",
    "A realistic image of a tranquil forest glade with shafts of sunlight filtering through the trees.",
    "A realistic image of a cozy mountain lodge nestled in the shadow of towering peaks.",
    "A realistic image of a lively city waterfront with boats coming and going from the docks.",
    "A realistic image of a peaceful country path winding through fields of golden wheat.",
    "A realistic image of a bustling city market with vendors selling fresh fruit and vegetables.",
    "A realistic image of a serene woodland stream with water bubbling over smooth stones.",
    "A realistic image of a picturesque coastal village with colorful houses and fishing boats.",
    "A realistic image of a tranquil forest clearing with a carpet of spring wildflowers.",
    "A realistic image of a bustling city square with street performers and outdoor cafes.",
    "A realistic image of a cozy village pub with a roaring fire and wooden beams.",
    "A realistic image of a vibrant city boulevard with flower-filled medians and outdoor seating.",
    "A realistic image of a serene mountain valley with a winding river and grazing deer.",
    "A realistic image of a bustling city market with vendors selling handmade crafts and jewelry.",
    "A realistic image of a peaceful country road bordered by fields of sunflowers.",
    "A realistic image of a quaint village green with a maypole and dancing villagers.",
    "A realistic image of a tranquil forest glade with a small waterfall cascading into a pool below.",
    "A realistic image of a cozy mountain retreat with panoramic views of snow-capped peaks.",
    "A realistic image of a bustling city waterfront with cafes and seafood restaurants.",
    "A realistic image of a peaceful country lane bordered by ancient stone walls and hedgerows.",
    "A realistic image of a bustling city market with vendors selling local cheeses and wines.",
    "A realistic image of a serene woodland path with dappled sunlight filtering through the trees.",
    "A realistic image of a picturesque coastal village with a harbor full of fishing boats.",
    "A realistic image of a tranquil forest clearing with a carpet of autumn leaves.",
    "A realistic image of a bustling city square with street performers and market stalls.",
    "A realistic image of a cozy village inn with a thatched roof and flower-filled garden.",
    "A realistic image of a vibrant city boulevard with street vendors and outdoor art installations.",
    "A realistic image of a serene mountain lake surrounded by pine forests and rocky cliffs.",
    "A realistic image of a bustling city market with vendors selling fresh flowers and produce.",
    "A realistic image of a peaceful country path winding through fields of lavender.",
    "A realistic image of a quaint village green with a cricket match in progress.",
    "A realistic image of a tranquil forest glade with sunlight streaming through the trees.",
    "A realistic image of a cozy mountain lodge nestled in the shadow of towering peaks.",
    "A realistic image of a lively city waterfront with boats coming and going from the docks.",
    "A realistic image of a peaceful country road bordered by fields of golden wheat.",
    "A realistic image of a bustling city market with vendors selling handmade crafts and jewelry.",
    "A realistic image of a serene woodland stream with water bubbling over smooth stones.",
    "A realistic image of a picturesque coastal village with colorful houses and fishing boats.",
    "A realistic image of a tranquil forest clearing with a carpet of spring wildflowers.",
    "A realistic image of a bustling city square with street performers and outdoor cafes.",
    "A realistic image of a cozy village pub with a roaring fire and wooden beams.",
    "A realistic image of a vibrant city boulevard with flower-filled medians and outdoor seating.",
    "A realistic image of a serene mountain valley with a winding river and grazing deer.",
    "A realistic image of a bustling city market with vendors selling handmade crafts and jewelry.",
    "A realistic image of a peaceful country road bordered by fields of sunflowers.",
    "A realistic image of a quaint village green with a maypole and dancing villagers.",
    "A realistic image of a tranquil forest glade with a small waterfall cascading into a pool below.",
    "A realistic image of a cozy mountain retreat with panoramic views of snow-capped peaks.",
    "A realistic image of a bustling city waterfront with cafes and seafood restaurants.",
    "A realistic image of a peaceful country lane bordered by ancient stone walls and hedgerows.",
    "A realistic image of a bustling city market with vendors selling local cheeses and wines.",
    "A realistic image of a serene woodland path with dappled sunlight filtering through the trees.",
    "A realistic image of a picturesque coastal village with a harbor full of fishing boats.",
    "A realistic image of a tranquil forest clearing with a carpet of autumn leaves.",
    "A realistic image of a bustling city square with street performers and market stalls.",
    "A realistic image of a cozy village inn with a thatched roof and flower-filled garden.",
    "A realistic image of a vibrant city boulevard with street vendors and outdoor art installations.",
    "A realistic image of a serene mountain lake surrounded by pine forests and rocky cliffs.",
    "A realistic image of a bustling city market with vendors selling fresh flowers and produce.",
    "A realistic image of a peaceful country path winding through fields of lavender."
];


export default promptArr;